version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        - ARCH
    image: django-lazy-srcset_local_django
    container_name: django-lazy-srcset-local-django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: "python3 manage.py runserver 0.0.0.0:8000"
